spec:
  template:
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag }}-{{ .Values.image.arch | default "amd64" }}"
          env:
            - name: TELE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-project-secret
                  key: tele_token
